/**
 * Generated by apps/api/scripts/export-contracts.mjs — do not hand-edit.
 * Regenerate: cd apps/api && npm run export:contracts
 */

/** @deprecated Prefer @/lib/api/generated — kept for existing imports */
export type {
  EmployeeAssignment,
  EmployeeListItem,
  EmployeesResponse,
} from '../generated/types'
