import { afterAll,beforeAll,describe,expect,it } from 'vitest'
import { createDb,type Db } from '../src/infrastructure/db/pool.js'
import { createCatalogRepository,type CatalogRepository } from '../src/infrastructure/db/catalog-repository.js'
import { testEnv } from './helpers.js'
const enabled=process.env.RUN_SUPABASE_INTEGRATION==='1'&&Boolean(process.env.DATABASE_URL)
const actor='d2922e19-bfbc-4a15-9a51-af40336ce9da'
describe.skipIf(!enabled)('Phase 4B PostgreSQL real integration',()=>{
 let db:Db,repo:CatalogRepository,supplierId:string;const marker=`P4B-${Date.now()}`
 beforeAll(async()=>{db=createDb(testEnv({DATABASE_URL:process.env.DATABASE_URL!}));repo=createCatalogRepository(db);supplierId=String((await repo.createSupplier({razonSocial:marker,cuit:marker,domicilio:null,telefono:null,provincia:null,condicionPagoDefault:null})).id)})
 afterAll(async()=>{if(db){await db.query("delete from public.catalog_operation_idempotency where actor_id=$1 and idempotency_key like $2",[actor,`${marker}%`]);await db.query('delete from public.articulos_proveedor_pendientes where proveedor_id=$1',[supplierId]);await db.query('delete from public.articulos_proveedor where proveedor_id=$1',[supplierId]);await db.query('delete from public.articulos where nombre like $1',[`${marker}%`]);await db.query('delete from public.proveedores where id=$1',[supplierId]);await db.close()}})
 it('generates unique ART codes concurrently in the real DB',async()=>{const created=await Promise.all(Array.from({length:8},(_,i)=>repo.createArticle({nombre:`${marker}-concurrent-${i}`,categoria:null,unidad:null,proveedorHabitualId:null})));const codes=created.map(r=>String(r.codigo_interno));expect(new Set(codes).size).toBe(8);codes.forEach(code=>expect(code).toMatch(/^ART-\d{4,}$/))})
 it('same idempotency key is one effective import and replays after response loss',async()=>{const rows=[{fila:2,codigoInterno:`${marker}-I`,nombre:`${marker}-import`,categoria:null,unidad:null}];const key=`${marker}-import`;const payloadHash='same';const [a,b]=await Promise.all([repo.importArticles(rows,{actorId:actor,key,payloadHash}),repo.importArticles(rows,{actorId:actor,key,payloadHash})]);expect([a.replayed,b.replayed].sort()).toEqual([false,true]);const retry=await repo.importArticles(rows,{actorId:actor,key,payloadHash});expect(retry).toEqual(expect.objectContaining({replayed:true,response:a.response}));expect(Number((await db.query('select count(*) from public.articulos where codigo_interno=$1',[`${marker}-I`])).rows[0].count)).toBe(1);await expect(repo.importArticles([{...rows[0],nombre:'different'}],{actorId:actor,key,payloadHash:'different'})).rejects.toMatchObject({status:409})})
 it('different key permits a legitimate new import',async()=>{const row={fila:2,codigoInterno:`${marker}-I2`,nombre:`${marker}-import2`,categoria:null,unidad:null};await repo.importArticles([row],{actorId:actor,key:`${marker}-different`,payloadHash:'different-key'});expect(Number((await db.query('select count(*) from public.articulos where codigo_interno=$1',[row.codigoInterno])).rows[0].count)).toBe(1)})
 it('rolls back the complete import on an intermediate conflict',async()=>{const code=`${marker}-ROLLBACK`;await expect(repo.importArticles([{fila:2,codigoInterno:code,nombre:`${marker}-rollback-a`,categoria:null,unidad:null},{fila:3,codigoInterno:code,nombre:`${marker}-rollback-b`,categoria:null,unidad:null}],{actorId:actor,key:`${marker}-rollback`,payloadHash:'rollback'})).rejects.toMatchObject({status:409});expect(Number((await db.query('select count(*) from public.articulos where codigo_interno=$1',[code])).rows[0].count)).toBe(0)})
 it('price list apply is idempotent and persists one relation',async()=>{const article=await repo.createArticle({codigoInterno:`${marker}-PRICE`,nombre:`${marker}-price`,categoria:null,unidad:null,proveedorHabitualId:null});const input={proveedorId:supplierId,archivoOrigen:'test.xlsx',rows:[{fila:2,codigoProveedor:`${marker}-CP`,codigoInterno:`${marker}-PRICE`,nombreProveedor:'Precio',precio:123}]};const key=`${marker}-price`;const payloadHash='price';const [a,b]=await Promise.all([repo.applyPriceList(input,{actorId:actor,key,payloadHash}),repo.applyPriceList(input,{actorId:actor,key,payloadHash})]);expect([a.replayed,b.replayed].sort()).toEqual([false,true]);expect(Number((await db.query('select count(*) from public.articulos_proveedor where proveedor_id=$1 and articulo_id=$2',[supplierId,article.id])).rows[0].count)).toBe(1)})
 it('previews imports and price lists without writes',async()=>{const beforeArticles=Number((await db.query('select count(*) from public.articulos')).rows[0].count),beforeRelations=Number((await db.query('select count(*) from public.articulos_proveedor')).rows[0].count),beforePending=Number((await db.query('select count(*) from public.articulos_proveedor_pendientes')).rows[0].count);await repo.previewArticleImport([{fila:2,codigoInterno:`${marker}-PREVIEW`,nombre:'Preview',categoria:null,unidad:null}]);await repo.previewPriceList({proveedorId:supplierId,archivoOrigen:'preview.xlsx',rows:[{fila:2,codigoProveedor:'P',codigoInterno:'missing',nombreProveedor:'Preview',precio:1}]});expect(Number((await db.query('select count(*) from public.articulos')).rows[0].count)).toBe(beforeArticles);expect(Number((await db.query('select count(*) from public.articulos_proveedor')).rows[0].count)).toBe(beforeRelations);expect(Number((await db.query('select count(*) from public.articulos_proveedor_pendientes')).rows[0].count)).toBe(beforePending)})
 it('rolls back a price list after an intermediate DB failure',async()=>{const article=await repo.createArticle({codigoInterno:`${marker}-PRICE-RB`,nombre:`${marker}-price-rb`,categoria:null,unidad:null,proveedorHabitualId:null});const input={proveedorId:supplierId,archivoOrigen:'rollback.xlsx',rows:[{fila:2,codigoProveedor:`${marker}-RB1`,codigoInterno:String(article.codigo_interno),nombreProveedor:'OK',precio:10},{fila:3,codigoProveedor:`${marker}-RB2`,codigoInterno:'',nombreProveedor:'FAIL',precio:'invalid'}]};await expect(repo.applyPriceList(input,{actorId:actor,key:`${marker}-price-rb`,payloadHash:'price-rb'})).rejects.toBeTruthy();expect(Number((await db.query('select count(*) from public.articulos_proveedor where proveedor_id=$1 and codigo_proveedor=$2',[supplierId,`${marker}-RB1`])).rows[0].count)).toBe(0)})
 it('rolls back pending resolution when relation insert conflicts',async()=>{const article=await repo.createArticle({codigoInterno:`${marker}-RESOLVE`,nombre:`${marker}-resolve`,categoria:null,unidad:null,proveedorHabitualId:null});const code=`${marker}-DUP`;await repo.createRelation(String(article.id),{proveedorId:supplierId,codigoProveedor:code,nombreProveedor:null,precio:1});const pending=(await db.query('insert into public.articulos_proveedor_pendientes(proveedor_id,codigo_proveedor,nombre_proveedor,precio) values($1,$2,$3,$4) returning id',[supplierId,code,'Pending',2])).rows[0];await expect(repo.resolvePending(String(pending.id),String(article.id))).rejects.toBeTruthy();expect((await db.query('select resuelto from public.articulos_proveedor_pendientes where id=$1',[pending.id])).rows[0].resuelto).toBe(false)})
})
