import { afterEach,describe,expect,it,vi } from 'vitest'
import type { FastifyInstance } from 'fastify'
import { buildApp } from '../src/app.js'
import { createProfileStubDb,signAccessToken,testEnv } from './helpers.js'
import type { CatalogRepository } from '../src/infrastructure/db/catalog-repository.js'
const USER='22222222-2222-4222-8222-222222222222',ID='33333333-3333-4333-8333-333333333333',REL='44444444-4444-4444-8444-444444444444'
const supplier={id:ID,razon_social:'Proveedor',cuit:'20',activo:true},article={id:ID,codigo_interno:'ART-0001',nombre:'Artículo',activo:true},relation={id:REL,articulo_id:ID,proveedor_id:ID,precio:10}
const apps:FastifyInstance[]=[];afterEach(async()=>Promise.all(apps.splice(0).map(a=>a.close())))
function repo():CatalogRepository{return {listSuppliers:vi.fn(async()=>[supplier]),supplier:vi.fn(async()=>supplier),supplierArticles:vi.fn(async()=>[]),createSupplier:vi.fn(async()=>supplier),updateSupplier:vi.fn(async()=>supplier),supplierStatus:vi.fn(async()=>supplier),listArticles:vi.fn(async()=>[article]),article:vi.fn(async()=>article),createArticle:vi.fn(async()=>article),updateArticle:vi.fn(async()=>article),articleStatus:vi.fn(async()=>article),relations:vi.fn(async()=>[relation]),createRelation:vi.fn(async()=>relation),updateRelation:vi.fn(async()=>relation),pending:vi.fn(async()=>[]),resolvePending:vi.fn(async()=>relation),previewArticleImport:vi.fn(async()=>({total:1,validas:1,invalidas:0,nuevos:1,actualizaciones:0,duplicados:[],conflictos:0,errores:[]})),previewPriceList:vi.fn(async()=>({proveedorId:ID,total:1,validas:1,invalidas:0,matchesExistentes:0,relacionesNuevas:1,pendientesNuevas:0,pendientesActualizadas:0,duplicados:[],errores:[]})),executeIdempotent:vi.fn(),importArticles:vi.fn(async()=>({replayed:false,response:{creados:1,actualizados:0}})),applyPriceList:vi.fn(async()=>({replayed:false,response:{actualizados:1,vinculadosPorCodigoInterno:0,pendientesNuevas:0,pendientesActualizadas:0}}))} as unknown as CatalogRepository}
async function app(role:string){const a=await buildApp(testEnv(),{db:createProfileStubDb({profile:{id:USER,nombre_completo:'User',rol:role}}),catalogRepo:repo()});apps.push(a);await a.ready();return a}async function auth(){return{authorization:`Bearer ${await signAccessToken({sub:USER})}`}}
describe('Phase 4B HTTP',()=>{
 it('requires auth and denies supervisor/auditoria',async()=>{expect((await (await app('admin')).inject({method:'GET',url:'/v1/suppliers'})).statusCode).toBe(401);for(const role of ['supervisor','auditoria'])expect((await (await app(role)).inject({method:'POST',url:'/v1/suppliers',headers:await auth(),payload:{razonSocial:'X',cuit:'1'}})).statusCode).toBe(403)})
 it.each(['admin','gerente','compras'])('allows %s catalog operations',async role=>{const a=await app(role),headers=await auth();expect((await a.inject({method:'GET',url:'/v1/suppliers',headers})).statusCode).toBe(200);expect((await a.inject({method:'POST',url:'/v1/articles',headers,payload:{nombre:'A'}})).statusCode).toBe(201);expect((await a.inject({method:'PATCH',url:`/v1/articles/${ID}/status`,headers,payload:{activo:false}})).statusCode).toBe(200)})
 it('previews and requires idempotency key only for apply',async()=>{const a=await app('compras'),headers=await auth(),payload={rows:[{fila:2,nombre:'A'}]};expect((await a.inject({method:'POST',url:'/v1/articles/import/preview',headers,payload})).statusCode).toBe(200);expect((await a.inject({method:'POST',url:'/v1/articles/import',headers,payload})).statusCode).toBe(400);expect((await a.inject({method:'POST',url:'/v1/articles/import',headers:{...headers,'idempotency-key':'key-1'},payload})).statusCode).toBe(200)})
})
