import { afterEach, describe, expect, it, vi } from 'vitest'
import type { FastifyInstance } from 'fastify'
import { buildApp } from '../src/app.js'
import { createProfileStubDb, signAccessToken, testEnv } from './helpers.js'
import type { ClientsRepository } from '../src/infrastructure/db/clients-repository.js'
import type { ClientQuotesStorage } from '../src/infrastructure/storage/client-quotes-storage.js'
import { notFound } from '../src/http/errors/app-error.js'

const USER='22222222-2222-4222-8222-222222222222', CLIENT='33333333-3333-4333-8333-333333333333', ADDRESS='44444444-4444-4444-8444-444444444444', QUOTE='55555555-5555-4555-8555-555555555555'
const client={id:CLIENT,nombre:'Cliente',cuit:null,persona_contacto:null,codigo_costos:null,presupuesto_4hs:0,presupuesto_8hs:0,domicilio:null,lleva_insumos:false,activo:true,created_at:'2026-01-01'}
const address={id:ADDRESS,cliente_id:CLIENT,alias:'Principal',direccion:'Calle 1',es_principal:true,activo:true,horario_atencion:null,supervisor_id:null,created_at:'2026-01-01'}
const quote={id:QUOTE,cliente_id:CLIENT,nombre_archivo:'x.pdf',storage_path:`${CLIENT}/x.pdf`,subido_por:USER,created_at:'2026-01-01'}
const apps:FastifyInstance[]=[]
afterEach(async()=>{await Promise.all(apps.splice(0).map(app=>app.close()))})
function repo():ClientsRepository{return {list:vi.fn(async()=>[client]),get:vi.fn(async()=>client),detail:vi.fn(async()=>({client,addresses:[address],quotes:[]})),create:vi.fn(async()=>client),update:vi.fn(async()=>client),addresses:vi.fn(async()=>[address]),createAddress:vi.fn(async()=>address),updateAddress:vi.fn(async()=>address),setAddressStatus:vi.fn(async()=>address),setPrincipal:vi.fn(async()=>address),listQuotes:vi.fn(async()=>[]),claimQuoteUpload:vi.fn(async(input:{storagePath:string})=>({state:'owner',storagePath:input.storagePath})),insertQuoteAndCompleteUpload:vi.fn(async()=>quote),failQuoteUpload:vi.fn(async()=>undefined),getQuote:vi.fn(async()=>quote),deleteQuote:vi.fn(async()=>quote),restoreQuote:vi.fn(async()=>undefined)} as unknown as ClientsRepository}
const storage:ClientQuotesStorage={upload:vi.fn(async()=>undefined),remove:vi.fn(async()=>undefined),signedUrl:vi.fn(async()=> 'https://signed.example/x')}
async function app(role:string,clientsRepo=repo()){const instance=await buildApp(testEnv(),{db:createProfileStubDb({profile:{id:USER,nombre_completo:'User',rol:role}}),clientsRepo,clientQuotesStorage:storage});apps.push(instance);await instance.ready();return instance}
async function auth(){return {authorization:`Bearer ${await signAccessToken({sub:USER})}`}}

describe('Phase 4A HTTP',()=>{
  it('requires authentication',async()=>{const a=await app('admin');expect((await a.inject({method:'GET',url:'/v1/clients'})).statusCode).toBe(401)})
  it('returns not found without leaking persistence details',async()=>{const clientsRepo=repo();vi.mocked(clientsRepo.detail).mockRejectedValue(notFound('Client not found'));const a=await app('admin',clientsRepo),headers=await auth();const response=await a.inject({method:'GET',url:`/v1/clients/${CLIENT}`,headers});expect(response.statusCode).toBe(404);expect(response.json()).toMatchObject({code:'not_found',detail:'Client not found'});expect(response.body).not.toContain('select ')})
  it('allows admin CRUD and validates payload',async()=>{const a=await app('admin'),headers=await auth();expect((await a.inject({method:'GET',url:'/v1/clients',headers})).statusCode).toBe(200);expect((await a.inject({method:'GET',url:`/v1/clients/${CLIENT}`,headers})).statusCode).toBe(200);expect((await a.inject({method:'POST',url:'/v1/clients',headers,payload:{nombre:'Nuevo'}})).statusCode).toBe(201);expect((await a.inject({method:'POST',url:'/v1/clients',headers,payload:{nombre:''}})).statusCode).toBe(400);expect((await a.inject({method:'PATCH',url:`/v1/clients/${CLIENT}`,headers,payload:{cuit:'20'}})).statusCode).toBe(200)})
  it('covers address lifecycle and principal',async()=>{const a=await app('compras'),headers=await auth();expect((await a.inject({method:'POST',url:`/v1/clients/${CLIENT}/addresses`,headers,payload:{alias:'Planta'}})).statusCode).toBe(201);expect((await a.inject({method:'PATCH',url:`/v1/clients/${CLIENT}/addresses/${ADDRESS}`,headers,payload:{direccion:'Nueva'}})).statusCode).toBe(200);expect((await a.inject({method:'PATCH',url:`/v1/clients/${CLIENT}/addresses/${ADDRESS}/status`,headers,payload:{activo:false}})).statusCode).toBe(200);expect((await a.inject({method:'POST',url:`/v1/clients/${CLIENT}/addresses/${ADDRESS}/principal`,headers})).statusCode).toBe(200)})
  it('uploads, signs and deletes quotes',async()=>{const a=await app('gerente'),headers={...(await auth()),'idempotency-key':'test-upload-1'},contentBase64=Buffer.from('%PDF-1.7\n%%EOF').toString('base64');expect((await a.inject({method:'POST',url:`/v1/clients/${CLIENT}/quotes`,headers,payload:{fileName:'x.pdf',contentBase64}})).statusCode).toBe(201);expect((await a.inject({method:'GET',url:`/v1/clients/${CLIENT}/quotes/${QUOTE}/download`,headers})).statusCode).toBe(200);expect((await a.inject({method:'DELETE',url:`/v1/clients/${CLIENT}/quotes/${QUOTE}`,headers})).statusCode).toBe(204)})
  it('requires Idempotency-Key for quote upload',async()=>{const a=await app('gerente'),headers=await auth(),contentBase64=Buffer.from('%PDF-1.7\n%%EOF').toString('base64');const response=await a.inject({method:'POST',url:`/v1/clients/${CLIENT}/quotes`,headers,payload:{fileName:'x.pdf',contentBase64}});expect(response.statusCode).toBe(400);expect(response.json()).toMatchObject({code:'bad_request',detail:'Idempotency-Key header is required'})})
  it('returns the original resource with 200 for an idempotent replay',async()=>{vi.clearAllMocks();const clientsRepo=repo();vi.mocked(clientsRepo.claimQuoteUpload).mockResolvedValue({state:'completed',quoteId:QUOTE} as never);const a=await app('gerente',clientsRepo),headers={...(await auth()),'idempotency-key':'replay-1'},contentBase64=Buffer.from('%PDF-1.7\n%%EOF').toString('base64');const response=await a.inject({method:'POST',url:`/v1/clients/${CLIENT}/quotes`,headers,payload:{fileName:'x.pdf',contentBase64}});expect(response.statusCode).toBe(200);expect(response.json()).toMatchObject({id:QUOTE});expect(storage.upload).not.toHaveBeenCalled()})
  it('denies supervisor and auditoria',async()=>{for(const role of ['supervisor','auditoria']){const a=await app(role),headers=await auth();expect((await a.inject({method:'POST',url:'/v1/clients',headers,payload:{nombre:'No'}})).statusCode).toBe(403)}})
})
