import { describe,expect,it } from 'vitest'

const ready=Boolean(process.env.RUN_SUPABASE_INTEGRATION==='1'&&process.env.SUPABASE_URL&&process.env.SUPABASE_ANON_KEY&&process.env.SUPABASE_SERVICE_ROLE_KEY&&process.env.POSTGREST_TEST_USER_JWT)
const nil='00000000-0000-0000-0000-000000000000'
describe.skipIf(!ready)('Phase 4A direct browser bypass negative',()=>{
  it.each([
    ['POST','clientes',{nombre:'DENY PHASE4A'}],['PATCH',`clientes?id=eq.${nil}`,{nombre:'DENY'}],['DELETE',`clientes?id=eq.${nil}`,null],
    ['POST','cliente_domicilios',{cliente_id:nil,alias:'DENY'}],['PATCH',`cliente_domicilios?id=eq.${nil}`,{activo:false}],['DELETE',`cliente_domicilios?id=eq.${nil}`,null],
    ['POST','cliente_presupuestos',{cliente_id:nil,storage_path:'deny/x.pdf',nombre_archivo:'x.pdf'}],['PATCH',`cliente_presupuestos?id=eq.${nil}`,{nombre_archivo:'deny.pdf'}],['DELETE',`cliente_presupuestos?id=eq.${nil}`,null],
  ])('%s /rest/v1/%s denied',async(method,resource,body)=>{const response=await fetch(`${process.env.SUPABASE_URL}/rest/v1/${resource}`,{method,headers:{apikey:process.env.SUPABASE_ANON_KEY!,authorization:`Bearer ${process.env.POSTGREST_TEST_USER_JWT}`,'content-type':'application/json',prefer:'return=minimal'},...(body?{body:JSON.stringify(body)}:{})});expect(response.ok).toBe(false);expect([401,403]).toContain(response.status)})
  it('storage upload is denied',async()=>{const response=await fetch(`${process.env.SUPABASE_URL}/storage/v1/object/presupuestos-clientes/deny/${crypto.randomUUID()}.pdf`,{method:'POST',headers:{apikey:process.env.SUPABASE_ANON_KEY!,authorization:`Bearer ${process.env.POSTGREST_TEST_USER_JWT}`,'content-type':'application/pdf'},body:'%PDF-1.7\n%%EOF'});expect(response.ok).toBe(false);expect([400,401,403]).toContain(response.status)})
  it('storage read and delete are denied for an existing private object',async()=>{const path=`deny/${crypto.randomUUID()}.pdf`,url=`${process.env.SUPABASE_URL}/storage/v1/object/presupuestos-clientes/${path}`,serviceHeaders={apikey:process.env.SUPABASE_SERVICE_ROLE_KEY!,authorization:`Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY!}`};const created=await fetch(url,{method:'POST',headers:{...serviceHeaders,'content-type':'application/pdf'},body:'%PDF-1.7\n%%EOF'});expect(created.ok).toBe(true);try{for(const method of ['GET','DELETE']){const response=await fetch(url,{method,headers:{apikey:process.env.SUPABASE_ANON_KEY!,authorization:`Bearer ${process.env.POSTGREST_TEST_USER_JWT}`}});expect(response.ok).toBe(false);expect([400,401,403,404]).toContain(response.status)}}finally{await fetch(url,{method:'DELETE',headers:serviceHeaders})}})
})
