import { afterEach,describe,expect,it,vi } from 'vitest'
import type { FastifyInstance } from 'fastify'
import type { PurchasesRepository } from '../src/infrastructure/db/purchases-repository.js'
import { buildApp } from '../src/app.js'
import { createProfileStubDb,signAccessToken,testEnv } from './helpers.js'
const USER='22222222-2222-4222-8222-222222222222',ID='33333333-3333-4333-8333-333333333333'
const apps:FastifyInstance[]=[];afterEach(async()=>Promise.all(apps.splice(0).map(a=>a.close())))
function repo(){const row={id:ID,estado:'borrador'};return{catalogs:vi.fn(async()=>({empresas:[],clientes:[],articulos:[],domicilios:[],proveedores:[],preciosProveedor:[]})),listRequests:vi.fn(async()=>[row]),requestDetail:vi.fn(async()=>row),saveRequest:vi.fn(async()=>row),transition:vi.fn(async()=>row),discard:vi.fn(async()=>row),previewImport:vi.fn(async()=>({total:1,valid:1,invalid:0,errors:[]})),applyImport:vi.fn(async()=>({replayed:false,response:{purchaseRequestIds:[ID]}})),applyAssignments:vi.fn(async()=>({replayed:false,response:{purchaseOrderIds:[ID],warehouseRequestId:null}})),listOrders:vi.fn(async()=>[row]),orderDetail:vi.fn(async()=>row),createOrder:vi.fn(async()=>row),listWarehouses:vi.fn(async()=>[row]),warehouseDetail:vi.fn(async()=>row),duplicate:vi.fn(async()=>row)} as unknown as PurchasesRepository}
async function app(role:string){const a=await buildApp(testEnv(),{db:createProfileStubDb({profile:{id:USER,nombre_completo:'User',rol:role}}),purchasesRepo:repo()});apps.push(a);await a.ready();return a}async function auth(){return{authorization:`Bearer ${await signAccessToken({sub:USER})}`}}
describe('Phase 4C HTTP and RBAC',()=>{
 it('requires authentication and denies supervisor and auditoria mutations',async()=>{expect((await(await app('admin')).inject({method:'GET',url:'/v1/purchase-requests'})).statusCode).toBe(401);for(const role of ['supervisor','auditoria'])expect((await(await app(role)).inject({method:'POST',url:'/v1/purchase-requests',headers:await auth(),payload:{}})).statusCode).toBe(403)})
 it.each(['admin','gerente','compras'])('allows %s purchase reads and validated creates',async role=>{const a=await app(role),headers=await auth();expect((await a.inject({method:'GET',url:'/v1/purchases/catalogs',headers})).statusCode).toBe(200);expect((await a.inject({method:'POST',url:'/v1/purchase-requests',headers,payload:{empresaId:ID,clienteId:ID,items:[{articuloId:ID,cantidad:1}]}})).statusCode).toBe(201)})
 it('requires idempotency keys for import apply and assignments',async()=>{const a=await app('compras'),headers=await auth();expect((await a.inject({method:'POST',url:'/v1/purchase-requests/import/apply',headers,payload:{empresaId:ID,orders:[{clienteId:ID,items:[{articuloId:ID,cantidad:1}]}]}})).statusCode).toBe(400);expect((await a.inject({method:'POST',url:`/v1/purchase-requests/${ID}/assignments`,headers,payload:{items:[{pedidoCompraItemId:ID,destino:'deposito',cantidad:1}]}})).statusCode).toBe(400)})
})
