import { afterAll,beforeAll,describe,expect,it } from 'vitest'
import pg from 'pg'
const url=process.env.MIGRATIONS_DATABASE_URL
const enabled=process.env.RUN_SUPABASE_INTEGRATION==='1'&&Boolean(url)
describe.skipIf(!enabled)('Phase 4C effective database validation',()=>{
 let pool:pg.Pool
 beforeAll(()=>{pool=new pg.Pool({connectionString:url,ssl:/supabase\.co|pooler\.supabase/i.test(url??'')?{rejectUnauthorized:false}:undefined,max:2})})
 afterAll(async()=>pool?.end())
 it('records every 4C migration with checksum',async()=>{const rows=(await pool.query("select filename,checksum from app_migrations.forward_history where filename like '%phase4c%' order by filename")).rows;expect(rows.map(r=>r.filename)).toEqual(['20260929110000_phase4c_purchases_api.sql','20260929111000_phase4c_company_catalog_access.sql','20260929112000_phase4c_client_catalog_access.sql','20260929113000_phase4c_purchase_item_price_check.sql']);rows.forEach(r=>expect(String(r.checksum)).toMatch(/^[a-f0-9]{64}$/))})
 it('has effective unique/check/FK constraints, numbering triggers and allocation indexes',async()=>{const constraints=(await pool.query("select conname,contype from pg_constraint where conrelid=any(array['public.pedidos_compra'::regclass,'public.pedidos_compra_items'::regclass,'public.ordenes_compra'::regclass,'public.ordenes_compra_items'::regclass,'public.pedidos_deposito'::regclass,'public.pedidos_deposito_items'::regclass])")).rows;expect(constraints.some(r=>r.contype==='u'&&r.conname==='pedidos_compra_numero_pedido_key')).toBe(true);expect(constraints.filter(r=>r.contype==='f').length).toBeGreaterThanOrEqual(12);expect(constraints.filter(r=>r.contype==='c').length).toBeGreaterThanOrEqual(6);const triggers=(await pool.query("select tgname from pg_trigger where not tgisinternal and tgrelid=any(array['public.pedidos_compra'::regclass,'public.ordenes_compra'::regclass,'public.pedidos_deposito'::regclass])")).rows.map(r=>r.tgname);expect(triggers).toEqual(expect.arrayContaining(['trg_pedidos_compra_set_numero','trg_ordenes_compra_set_numero','trg_pedidos_deposito_set_numero']));const indexes=(await pool.query("select indexname from pg_indexes where schemaname='public' and indexname like '%pedido_compra_item_idx'")).rows.map(r=>r.indexname);expect(indexes).toEqual(expect.arrayContaining(['ordenes_compra_items_pedido_compra_item_idx','pedidos_deposito_items_pedido_compra_item_idx']))})
 it('keeps RLS on, grants runtime DML, and grants authenticated no DML',async()=>{const tables=['pedidos_compra','pedidos_compra_items','ordenes_compra','ordenes_compra_items','pedidos_deposito','pedidos_deposito_items'];const rls=(await pool.query('select relname,relrowsecurity from pg_class where oid=any($1::regclass[])',[tables.map(t=>`public.${t}`)])).rows;expect(rls).toHaveLength(6);rls.forEach(r=>expect(r.relrowsecurity).toBe(true));const browser=(await pool.query("select count(*)::int n from information_schema.role_table_grants where grantee='authenticated' and table_schema='public' and table_name=any($1) and privilege_type=any(array['INSERT','UPDATE','DELETE'])",[tables])).rows[0].n;expect(browser).toBe(0);const runtime=(await pool.query("select table_name,count(distinct privilege_type)::int n from information_schema.role_table_grants where grantee='dinamic_api' and table_schema='public' and table_name=any($1) and privilege_type=any(array['SELECT','INSERT','UPDATE','DELETE']) group by table_name",[tables])).rows;expect(runtime).toHaveLength(6);runtime.forEach(r=>expect(r.n).toBe(4));const role=(await pool.query("select rolsuper,rolcreatedb,rolcreaterole,rolreplication,rolbypassrls from pg_roles where rolname='dinamic_api'")).rows[0];expect(role).toEqual({rolsuper:false,rolcreatedb:false,rolcreaterole:false,rolreplication:false,rolbypassrls:false})})
 it('has runtime RLS policies and persistent idempotency',async()=>{const policies=(await pool.query("select tablename,policyname from pg_policies where schemaname='public' and roles @> array['dinamic_api']::name[]")).rows;for(const table of ['pedidos_compra','pedidos_compra_items','ordenes_compra','ordenes_compra_items','pedidos_deposito','pedidos_deposito_items','purchase_operation_idempotency'])expect(policies.some(p=>p.tablename===table)).toBe(true);const columns=(await pool.query("select column_name from information_schema.columns where table_schema='public' and table_name='purchase_operation_idempotency'")).rows.map(r=>r.column_name);expect(columns).toEqual(expect.arrayContaining(['actor_id','operation','idempotency_key','payload_hash','status','response']))})
})
