import { afterAll,beforeAll,describe,expect,it,vi } from 'vitest'
import { createDb,type Db } from '../src/infrastructure/db/pool.js'
import { createPurchasesRepository,type PurchasesRepository } from '../src/infrastructure/db/purchases-repository.js'
import { testEnv } from './helpers.js'
const enabled=process.env.RUN_SUPABASE_INTEGRATION==='1'&&Boolean(process.env.DATABASE_URL)
vi.setConfig({testTimeout:30_000,hookTimeout:30_000})
describe.skipIf(!enabled)('Phase 4C PostgreSQL real integration',()=>{
 let db:Db,repo:PurchasesRepository,actor:string,company:string,client:string,article:string,supplier:string
 const requestIds:string[]=[],orderIds:string[]=[],warehouseIds:string[]=[],keys:string[]=[];const marker=`P4C-${Date.now()}`
 beforeAll(async()=>{db=createDb(testEnv({DATABASE_URL:process.env.DATABASE_URL!}));repo=createPurchasesRepository(db);const refs=(await db.query("select (select id from public.perfiles order by id limit 1) actor,(select id from public.empresas where activo=true order by id limit 1) company,(select id from public.clientes order by id limit 1) client,(select id from public.articulos where activo=true order by id limit 1) article,(select id from public.proveedores where activo=true order by id limit 1) supplier")).rows[0];actor=String(refs.actor);company=String(refs.company);client=String(refs.client);article=String(refs.article);supplier=String(refs.supplier);expect([actor,company,client,article,supplier].every(x=>x&&x!=='null')).toBe(true)})
 afterAll(async()=>{if(!db)return;await db.query('delete from public.ordenes_compra_items where oc_id=any($1::uuid[])',[orderIds]);await db.query('delete from public.pedidos_deposito_items where pedido_deposito_id=any($1::uuid[])',[warehouseIds]);await db.query('delete from public.ordenes_compra where id=any($1::uuid[])',[orderIds]);await db.query('delete from public.pedidos_deposito where id=any($1::uuid[])',[warehouseIds]);await db.query('delete from public.pedidos_compra_items where pedido_id=any($1::uuid[])',[requestIds]);await db.query('delete from public.pedidos_compra where id=any($1::uuid[])',[requestIds]);await db.query('delete from public.purchase_operation_idempotency where actor_id=$1 and idempotency_key=any($2::text[])',[actor,keys]);await db.close()})
 const input=(quantity=5)=>({empresaId:company,clienteId:client,observacionesGenerales:marker,estado:'borrador' as const,items:[{articuloId:article,cantidad:quantity,observaciones:null}]})
 it('creates and edits header/items atomically and rolls back after deleting old items',async()=>{const created=await repo.saveRequest(input(),actor);requestIds.push(String(created.id));await expect(repo.saveRequest({...input(),items:[{articuloId:article,cantidad:2,observaciones:'invalid\u0000text'}]},actor,String(created.id))).rejects.toBeTruthy();const after=await repo.requestDetail(String(created.id));expect(after.pedidos_compra_items).toHaveLength(1);expect(Number(after.pedidos_compra_items[0]!.cantidad)).toBe(5)})
 it('generates concurrent-safe unique request numbers',async()=>{const rows=await Promise.all(Array.from({length:6},()=>repo.saveRequest(input(1),actor)));requestIds.push(...rows.map(r=>String(r.id)));const numbers=rows.map(r=>String(r.numero_pedido));expect(new Set(numbers).size).toBe(6);numbers.forEach(n=>expect(n).toMatch(/^PED-\d{4,}$/))})
 it('generates concurrent-safe OC and warehouse numbers',async()=>{const orders=await Promise.all(Array.from({length:4},()=>repo.createOrder({empresaId:company,proveedorId:supplier,clienteId:client,items:[{articuloId:article,cantidad:1,precioUnitario:10}]},actor)));orderIds.push(...orders.map(o=>String(o.id)));const orderNumbers=orders.map(o=>String(o.numero_oc));expect(new Set(orderNumbers).size).toBe(4);orderNumbers.forEach(n=>expect(n).toMatch(/^OC-\d{4,}$/));const sources=await Promise.all(Array.from({length:4},()=>repo.saveRequest(input(1),actor)));requestIds.push(...sources.map(s=>String(s.id)));await Promise.all(sources.map(s=>repo.transition('pedidos_compra',String(s.id),'enviada')));const generated=await Promise.all(sources.map((s,i)=>{const key=`${marker}-dep-num-${i}`;keys.push(key);return repo.applyAssignments(String(s.id),{items:[{pedidoCompraItemId:String((s.pedidos_compra_items[0] as {id:string}).id),destino:'deposito',cantidad:1}]},key,actor)}));const ids=generated.map(g=>g.response.warehouseRequestId!);warehouseIds.push(...ids);const warehouses=await Promise.all(ids.map(id=>repo.warehouseDetail(id)));const numbers=warehouses.map(w=>String(w.numero_pedido_deposito));expect(new Set(numbers).size).toBe(4);numbers.forEach(n=>expect(n).toMatch(/^DEP-\d{4,}$/))})
 it('serializes assignments, prevents over-allocation and replays the same key',async()=>{const created=await repo.saveRequest(input(),actor);requestIds.push(String(created.id));await repo.transition('pedidos_compra',String(created.id),'enviada');const item=created.pedidos_compra_items[0] as {id:string};const payload={items:[{pedidoCompraItemId:item.id,destino:'proveedor' as const,proveedorId:supplier,cantidad:5,precioUnitario:10,observaciones:null}]};const key=`${marker}-assign`;keys.push(key);const [a,b]=await Promise.all([repo.applyAssignments(String(created.id),payload,key,actor),repo.applyAssignments(String(created.id),payload,key,actor)]);expect([a.replayed,b.replayed].sort()).toEqual([false,true]);orderIds.push(...a.response.purchaseOrderIds);expect(new Set(a.response.purchaseOrderIds).size).toBe(1);const other=`${marker}-over`;keys.push(other);await expect(repo.applyAssignments(String(created.id),{items:[{...payload.items[0],cantidad:1}]},other,actor)).rejects.toMatchObject({status:409})})
 it('generates warehouse header/items atomically and enforces state machine',async()=>{const created=await repo.saveRequest(input(3),actor);requestIds.push(String(created.id));await repo.transition('pedidos_compra',String(created.id),'enviada');const item=created.pedidos_compra_items[0] as {id:string};const key=`${marker}-warehouse`;keys.push(key);const result=await repo.applyAssignments(String(created.id),{items:[{pedidoCompraItemId:item.id,destino:'deposito',cantidad:3}]},key,actor);expect(result.response.warehouseRequestId).toBeTruthy();warehouseIds.push(result.response.warehouseRequestId!);await expect(repo.transition('pedidos_deposito',result.response.warehouseRequestId!,'recepcionada')).rejects.toMatchObject({status:409});await repo.transition('pedidos_deposito',result.response.warehouseRequestId!,'enviada');await repo.transition('pedidos_deposito',result.response.warehouseRequestId!,'recepcionada')})
 it('previews without writes and applies import atomically/idempotently',async()=>{const payload={empresaId:company,orders:[{clienteId:client,lugarEnvioAlias:marker,items:[{articuloId:article,cantidad:2}]}]};const before=Number((await db.query('select count(*) from public.pedidos_compra where lugar_envio_alias=$1',[marker])).rows[0].count);expect((await repo.previewImport(payload)).valid).toBe(1);expect(Number((await db.query('select count(*) from public.pedidos_compra where lugar_envio_alias=$1',[marker])).rows[0].count)).toBe(before);const key=`${marker}-import`;keys.push(key);const [a,b]=await Promise.all([repo.applyImport(payload,key,actor),repo.applyImport(payload,key,actor)]);expect([a.replayed,b.replayed].sort()).toEqual([false,true]);requestIds.push(...a.response.purchaseRequestIds);expect(Number((await db.query('select count(*) from public.pedidos_compra where lugar_envio_alias=$1',[marker])).rows[0].count)).toBe(before+1);await expect(repo.applyImport({...payload,orders:[{...payload.orders[0],items:[{articuloId:article,cantidad:3}]}]},key,actor)).rejects.toMatchObject({status:409})})
 it('rolls back OC and warehouse headers when an item insert fails',async()=>{const alias=`${marker}-rollback-header`;await expect(repo.createOrder({empresaId:company,proveedorId:supplier,clienteId:client,lugarEnvioAlias:alias,items:[{articuloId:article,cantidad:1,precioUnitario:10,observaciones:'bad\u0000item'}]},actor)).rejects.toBeTruthy();expect(Number((await db.query('select count(*) from public.ordenes_compra where lugar_envio_alias=$1',[alias])).rows[0].count)).toBe(0);const source=await repo.saveRequest(input(1),actor);requestIds.push(String(source.id));await repo.transition('pedidos_compra',String(source.id),'enviada');const key=`${marker}-dep-rollback`;keys.push(key);await expect(repo.applyAssignments(String(source.id),{lugarEnvioAlias:alias,items:[{pedidoCompraItemId:String((source.pedidos_compra_items[0] as {id:string}).id),destino:'deposito',cantidad:1,observaciones:'bad\u0000item'}]},key,actor)).rejects.toBeTruthy();expect(Number((await db.query('select count(*) from public.pedidos_deposito where lugar_envio_alias=$1',[alias])).rows[0].count)).toBe(0)})
 it('rolls back the complete import after a later item failure',async()=>{const alias=`${marker}-import-rollback`,payload={empresaId:company,orders:[{clienteId:client,lugarEnvioAlias:alias,items:[{articuloId:article,cantidad:1}]},{clienteId:client,lugarEnvioAlias:`${alias}-2`,items:[{articuloId:article,cantidad:1,observaciones:'bad\u0000item'}]}]};const key=`${marker}-import-rollback`;keys.push(key);await expect(repo.applyImport(payload,key,actor)).rejects.toBeTruthy();expect(Number((await db.query('select count(*) from public.pedidos_compra where lugar_envio_alias like $1',[`${alias}%`])).rows[0].count)).toBe(0)})
})
