#!/usr/bin/env python3
"""Long-line readability collector for Dinamic Clean audits (diagnostic only)."""

from __future__ import annotations

import json
import re
import sys
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from fnmatch import fnmatch
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[3]
CONFIG_PATH = REPO_ROOT / "scripts" / "audit" / "config" / "line-length.json"

EXIT_PASS = 0
EXIT_FINDINGS = 1
EXIT_NOT_RUN = 2
EXIT_ERROR = 3

URL_RE = re.compile(r"https?://[^\s'\"]+", re.I)
HASH_RE = re.compile(r"\b[0-9a-f]{32,}\b", re.I)
GENERATED_MARKERS = (
    "/** @generated",
    "// @generated",
    "DO NOT EDIT",
    "auto-generated",
    "autogenerated",
)


@dataclass
class LongLineFinding:
    file: str
    line: int
    length: int
    severity: str
    category: str
    content_kind: str
    side: str
    snippet: str


def load_config() -> dict[str, Any]:
    return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))


def matches_any(rel: str, patterns: list[str]) -> bool:
    return any(fnmatch(rel, pat) for pat in patterns)


def is_generated_file(path: Path, head: str) -> bool:
    rel = path.as_posix()
    if "/generated/" in rel or rel.endswith(".generated.ts"):
        return True
    lower = head[:2000].lower()
    return any(m.lower() in lower for m in GENERATED_MARKERS)


def iter_files(include: list[str], exclude: list[str]) -> list[Path]:
    files: list[Path] = []
    seen: set[str] = set()
    for pattern in include:
        for path in REPO_ROOT.glob(pattern):
            if not path.is_file():
                continue
            rel = path.relative_to(REPO_ROOT).as_posix()
            if rel in seen or matches_any(rel, exclude):
                continue
            seen.add(rel)
            files.append(path)
    return sorted(files, key=lambda p: p.as_posix())


def side_for(rel: str) -> str:
    if rel.startswith("apps/api/"):
        return "backend"
    if rel.startswith("src/"):
        return "frontend"
    return "other"


def severity_for(length: int, thresholds: dict[str, int]) -> str | None:
    if length > thresholds["severe"]:
        return "severe"
    if length > thresholds["high"]:
        return "high"
    if length > thresholds["warning"]:
        return "warning"
    return None


def strip_inline_comment(line: str) -> str:
    """Rough strip for classification; physical length uses full line."""
    if "//" in line:
        idx = line.find("//")
        if idx > 0 and line[idx - 1] != ":":
            return line[:idx].rstrip()
    return line


def inevitable_content(line: str, stripped: str) -> bool:
    s = stripped.strip()
    if not s:
        return False
    if URL_RE.search(s) and len(s.replace(" ", "")) - len(URL_RE.findall(s)) * 20 < 40:
        return True
    if HASH_RE.search(s) and len(s) > 160:
        rest = HASH_RE.sub("", s)
        if len(rest.strip()) < 30:
            return True
    # Mostly one quoted string
    if (s.count('"') >= 2 or s.count("'") >= 2) and not re.search(r"[{}();=<>]", s[:20]):
        quote = '"' if s.count('"') >= 2 else "'"
        parts = s.split(quote)
        if len(parts) >= 3:
            inner = max(parts, key=len)
            if len(inner) > len(s) * 0.65:
                return True
    return False


def classify_line(line: str, rel: str) -> tuple[str, str]:
    """Return (category, content_kind structural|inevitable_content)."""
    stripped = strip_inline_comment(line).strip()
    if inevitable_content(line, stripped):
        return "string_or_url", "inevitable_content"

    is_tsx = rel.endswith(".tsx")

    if stripped.startswith("import ") or stripped.startswith("export "):
        return "import_export", "structural"

    if is_tsx and ("<" in stripped and ("=" in stripped or "/>" in stripped or "</" in stripped)):
        if stripped.lstrip().startswith("<") or re.search(r"<\w+[\s/>]", stripped):
            return "jsx_props", "structural"

    if "?" in stripped and ":" in stripped and stripped.count("?") <= 3:
        return "ternary", "structural"

    if re.match(r"^(export\s+)?(async\s+)?function\s+\w+", stripped) or re.match(
        r"^(export\s+)?(async\s+)?\([^)]*\)\s*=>", stripped
    ):
        return "function_signature", "structural"

    if re.match(r"^(public|private|protected|static|readonly|\s)*[\w$]+\s*\([^)]*\)\s*[:{]", stripped):
        return "function_signature", "structural"

    if re.match(r"^(if|while|for|switch)\s*\(", stripped) or (
        "&&" in stripped or "||" in stripped
    ) and ("if " in stripped or stripped.startswith("(")):
        return "long_condition", "structural"

    if stripped.startswith(("{", "[")) or re.search(r"=\s*[\[{]", stripped):
        return "object_or_array_literal", "structural"

    call_like = stripped.count("(") >= 1 and stripped.count(")") >= 1
    if call_like and stripped.count(".") >= 2:
        return "chained_call", "structural"
    if call_like:
        return "function_call", "structural"

    if stripped.count('"') + stripped.count("'") > 4:
        return "string_or_url", "structural"

    return "other", "structural"


def truncate_snippet(line: str, max_chars: int) -> str:
    one = line.replace("\t", " ").strip()
    if len(one) <= max_chars:
        return one
    return one[: max_chars - 3] + "..."


def scan(cfg: dict[str, Any]) -> dict[str, Any]:
    if not cfg.get("enabled", True):
        return {"status": "NOT_RUN", "reason": "collector disabled in config"}

    thresholds = cfg.get("audit_thresholds") or {}
    for key in ("warning", "high", "severe"):
        if key not in thresholds:
            return {"status": "ERROR", "reason": f"missing audit_thresholds.{key}"}

    warn = int(thresholds["warning"])
    high = int(thresholds["high"])
    severe = int(thresholds["severe"])
    if not (0 < warn < high < severe):
        return {"status": "ERROR", "reason": "audit_thresholds must satisfy 0 < warning < high < severe"}

    include = list(cfg.get("include_globs") or [])
    exclude = list(cfg.get("exclude_globs") or [])
    snippet_max = int(cfg.get("snippet_max_chars") or 160)
    max_json = int(cfg.get("max_findings_in_json") or 10000)

    findings: list[LongLineFinding] = []
    files_scanned = 0

    for path in iter_files(include, exclude):
        rel = path.relative_to(REPO_ROOT).as_posix()
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            return {"status": "ERROR", "reason": f"cannot read {rel}: {exc}"}

        if is_generated_file(path, text):
            continue

        files_scanned += 1
        side = side_for(rel)
        for idx, line in enumerate(text.splitlines(), start=1):
            length = len(line)
            sev = severity_for(length, {"warning": warn, "high": high, "severe": severe})
            if sev is None:
                continue
            category, content_kind = classify_line(line, rel)
            findings.append(
                LongLineFinding(
                    file=rel,
                    line=idx,
                    length=length,
                    severity=sev,
                    category=category,
                    content_kind=content_kind,
                    side=side,
                    snippet=truncate_snippet(line, snippet_max),
                )
            )

    findings.sort(key=lambda f: (-f.length, f.file, f.line))

    over_120 = sum(1 for f in findings if f.length > warn)
    over_160 = sum(1 for f in findings if f.length > high)
    over_200 = sum(1 for f in findings if f.length > severe)

    by_category = Counter(f.category for f in findings)
    by_severity = Counter(f.severity for f in findings)
    by_side = Counter(f.side for f in findings)

    per_file = Counter(f.file for f in findings)
    top_files = per_file.most_common(20)
    top_lines = findings[:20]

    return {
        "status": "FINDINGS" if findings else "PASS",
        "thresholds": {"warning": warn, "high": high, "severe": severe},
        "files_scanned": files_scanned,
        "totals": {
            "over_warning": over_120,
            "over_high": over_160,
            "over_severe": over_200,
            "findings": len(findings),
        },
        "by_severity": dict(by_severity),
        "by_category": dict(by_category),
        "by_side": dict(by_side),
        "top_files": [{"file": f, "count": c} for f, c in top_files],
        "top_lines": [asdict(f) for f in top_lines],
        "findings": [asdict(f) for f in findings[:max_json]],
        "findings_truncated": len(findings) > max_json,
    }


def render_summary(report: dict[str, Any]) -> str:
    lines = ["# Line length / readability audit", ""]
    status = report.get("status")
    lines.append(f"STATUS: {status}")
    if status == "NOT_RUN":
        lines.append(f"REASON: {report.get('reason', '')}")
        return "\n".join(lines) + "\n"

    if status == "ERROR":
        lines.append(f"REASON: {report.get('reason', '')}")
        return "\n".join(lines) + "\n"

    t = report["thresholds"]
    lines.append(f"thresholds: warning>{t['warning']} high>{t['high']} severe>{t['severe']}")
    lines.append(f"files_scanned: {report.get('files_scanned', 0)}")
    tot = report["totals"]
    lines.append(f"lines_over_{t['warning']}: {tot['over_warning']}")
    lines.append(f"lines_over_{t['high']}: {tot['over_high']}")
    lines.append(f"lines_over_{t['severe']}: {tot['over_severe']}")
    lines.append("")
    lines.append("## By category")
    for cat, count in sorted(report.get("by_category", {}).items(), key=lambda x: -x[1]):
        lines.append(f"- {cat}: {count}")
    lines.append("")
    lines.append("## By side")
    for side, count in sorted(report.get("by_side", {}).items()):
        lines.append(f"- {side}: {count}")
    lines.append("")
    lines.append("## Top 20 files")
    for item in report.get("top_files", []):
        lines.append(f"- {item['count']} {item['file']}")
    lines.append("")
    lines.append("## Top 20 longest lines")
    for item in report.get("top_lines", []):
        lines.append(
            f"- {item['file']}:{item['line']} len={item['length']} "
            f"sev={item['severity']} cat={item['category']} kind={item['content_kind']}"
        )
        lines.append(f"  {item['snippet']}")
    if report.get("findings_truncated"):
        lines.append("")
        lines.append("(Full findings list truncated in JSON; counts above are complete.)")
    return "\n".join(lines) + "\n"


def main() -> int:
    out_txt = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    out_json = Path(sys.argv[2]) if len(sys.argv) > 2 else None

    try:
        cfg = load_config()
        report = scan(cfg)
    except Exception as exc:  # noqa: BLE001 — audit collector boundary
        report = {"status": "ERROR", "reason": str(exc)}

    status = report.get("status")
    if out_json:
        out_json.parent.mkdir(parents=True, exist_ok=True)
        out_json.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    body = render_summary(report)
    if out_txt:
        out_txt.parent.mkdir(parents=True, exist_ok=True)
        out_txt.write_text(body, encoding="utf-8")
    print(body)

    if status == "PASS":
        return EXIT_PASS
    if status == "FINDINGS":
        return EXIT_FINDINGS
    if status == "NOT_RUN":
        return EXIT_NOT_RUN
    return EXIT_ERROR


if __name__ == "__main__":
    raise SystemExit(main())
