'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import * as XLSX from 'xlsx'
import { createAuthenticatedBrowserApiClient } from '@/lib/api/browser'
import { normalizarPrecio } from '@/utils/normalizarPrecio'
import DescargarPlantillaListaPrecios from './DescargarPlantillaListaPrecios'
type Proveedor={id:string;razon_social:string};type Resumen={actualizados:number;vinculadosPorCodigoInterno:number;pendientesNuevas:number}
export default function CargaListaPrecios({proveedores}:{proveedores:Proveedor[]}){const [proveedorId,setProveedorId]=useState(''),[archivo,setArchivo]=useState<File|null>(null),[procesando,setProcesando]=useState(false),[error,setError]=useState(''),[resumen,setResumen]=useState<Resumen|null>(null);const router=useRouter();async function submit(e:React.FormEvent){e.preventDefault();setError('');setResumen(null);if(!proveedorId||!archivo){setError('Elegí proveedor y archivo Excel.');return}setProcesando(true);try{const libro=XLSX.read(await archivo.arrayBuffer(),{type:'array'});const raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(libro.Sheets[libro.SheetNames[0]]);if(!raw.length)throw new Error('El archivo no tiene filas.');const rows=raw.flatMap((r,index)=>{const precio=normalizarPrecio(r.precio);if(Number.isNaN(precio))throw new Error(`Precio inválido en fila ${index+2}`);const codigoInterno=String(r.codigo_interno??'').trim();return[{fila:index+2,codigoProveedor:String(r.codigo_proveedor??'').trim()||codigoInterno,codigoInterno,nombreProveedor:String(r.nombre_proveedor??'').trim(),precio}]});const result=await (await createAuthenticatedBrowserApiClient()).applyPriceList({proveedorId,archivoOrigen:archivo.name,rows},crypto.randomUUID());setResumen(result.response);setArchivo(null);router.refresh()}catch(err){setError(err instanceof Error?err.message:'Error al procesar la lista')}finally{setProcesando(false)}}return <div className="flex flex-col gap-4"><p className="text-sm text-slate-600">La API vuelve a validar y aplica la lista completa en una transacción; las líneas sin vínculo se guardan como pendientes.</p><DescargarPlantillaListaPrecios proveedorId={proveedorId}/><form onSubmit={submit} className="flex flex-wrap gap-2"><select value={proveedorId} onChange={e=>setProveedorId(e.target.value)} required className="px-3 py-2 border rounded-lg text-sm"><option value="">Elegí un proveedor...</option>{proveedores.map(p=><option key={p.id} value={p.id}>{p.razon_social}</option>)}</select><input type="file" accept=".xlsx" onChange={e=>setArchivo(e.target.files?.[0]??null)}/><button disabled={procesando} className="px-4 py-2 bg-teal-600 text-white text-sm rounded-lg disabled:opacity-50">{procesando?'Procesando...':'Importar lista de precios'}</button></form>{error&&<p className="text-rose-600 text-sm">{error}</p>}{resumen&&<p className="text-sm text-emerald-700">Precios actualizados: {resumen.actualizados}. Vinculados: {resumen.vinculadosPorCodigoInterno}. Pendientes: {resumen.pendientesNuevas}.</p>}</div>}
