import crypto from 'node:crypto'
import type pg from 'pg'
import type { Db } from './pool.js'
import { conflict, notFound } from '../../http/errors/app-error.js'
import type { ActionCreate, ActionUpdate, AuditListQuery, AuditSubmit, ChecklistCreate, PlanningBody, PlanningUpdate } from '../../http/schemas/audits.js'

const tx=async<T>(db:Db,run:(c:pg.PoolClient)=>Promise<T>)=>{const c=await db.pool.connect();try{await c.query('begin');const r=await run(c);await c.query('commit');return r}catch(e){await c.query('rollback');throw e}finally{c.release()}}
const one=<T>(rows:T[],m:string)=>{if(!rows[0])throw notFound(m);return rows[0]};const hash=(v:unknown)=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex')
export function createAuditsRepository(db:Db){
 const plans=async(q:AuditListQuery)=>{const p:unknown[]=[];const c:string[]=[];const v=(x:unknown)=>{p.push(x);return `$${p.length}`};if(q.estado)c.push(`p.estado=${v(q.estado)}`);if(q.supervisorId)c.push(`p.supervisor_id=${v(q.supervisorId)}`);if(q.desde)c.push(`p.fecha_propuesta>=${v(q.desde)}`);if(q.hasta)c.push(`p.fecha_propuesta<=${v(q.hasta)}`);const w=c.length?` where ${c.join(' and ')}`:'';const total=await db.query<{count:string}>(`select count(*)::text count from public.auditoria_planificaciones p${w}`,p);const rows=await db.query(`select p.*,jsonb_build_object('alias',d.alias,'direccion',d.direccion,'clientes',case when cl.id is null then null else jsonb_build_object('nombre',cl.nombre) end) cliente_domicilios,case when s.id is null then null else jsonb_build_object('nombre_completo',s.nombre_completo) end perfiles from public.auditoria_planificaciones p join public.cliente_domicilios d on d.id=p.alias_id left join public.clientes cl on cl.id=d.cliente_id left join public.perfiles s on s.id=p.supervisor_id${w} order by p.fecha_propuesta asc,p.id offset $${p.length+1} limit $${p.length+2}`,[...p,(q.page-1)*q.pageSize,q.pageSize]);return{items:rows.rows,page:q.page,pageSize:q.pageSize,total:Number(total.rows[0]?.count??0)}}
 const createPlanning=(v:PlanningBody)=>db.query('insert into public.auditoria_planificaciones(alias_id,fecha_propuesta,horario_desde,horario_hasta,supervisor_id,observaciones) values($1,$2,$3,$4,$5,$6) returning *',[v.aliasId,v.fechaPropuesta,v.horarioDesde,v.horarioHasta,v.supervisorId,v.observaciones]).then(x=>one(x.rows,'Planning creation failed'))
 const updatePlanning=(id:string,v:PlanningUpdate)=>tx(db,async c=>{const old=one((await c.query<{updated_at:string|null;estado:string}>('select updated_at,estado from public.auditoria_planificaciones where id=$1 for update',[id])).rows,'Planning not found');if(old.updated_at!==v.updatedAt)throw conflict('Planning was modified by another user');if(old.estado!=='planificada')throw conflict('Only planned audits may be edited');return one((await c.query('update public.auditoria_planificaciones set alias_id=$2,fecha_propuesta=$3,horario_desde=$4,horario_hasta=$5,supervisor_id=$6,observaciones=$7 where id=$1 returning *',[id,v.aliasId,v.fechaPropuesta,v.horarioDesde,v.horarioHasta,v.supervisorId,v.observaciones])).rows,'Planning not found')})
 const cancelPlanning=(id:string,updatedAt:string)=>tx(db,async c=>{const old=one((await c.query<{updated_at:string|null;estado:string}>('select updated_at,estado from public.auditoria_planificaciones where id=$1 for update',[id])).rows,'Planning not found');if(old.updated_at!==updatedAt)throw conflict('Planning was modified by another user');if(old.estado!=='planificada')throw conflict('Only planned audits may be cancelled');return one((await c.query("update public.auditoria_planificaciones set estado='cancelada' where id=$1 returning *",[id])).rows,'Planning not found')})
 const submit=async(v:AuditSubmit,actor:string,key:string)=>tx(db,async c=>{const h=hash(v);await c.query("insert into public.audits_operation_idempotency(actor_id,operation,idempotency_key,payload_hash,status) values($1,'audit_submit',$2,$3,'PROCESSING') on conflict do nothing",[actor,key,h]);const idem=one((await c.query<{payload_hash:string;status:string;response:unknown}>('select payload_hash,status,response from public.audits_operation_idempotency where actor_id=$1 and operation=$2 and idempotency_key=$3 for update',[actor,'audit_submit',key])).rows,'Idempotency unavailable');if(idem.payload_hash!==h)throw conflict('Idempotency-Key was already used with a different payload');if(idem.status==='COMPLETED')return{replayed:true,response:idem.response};if(v.planificacionId){const plan=one((await c.query<{estado:string;alias_id:string;supervisor_id:string}>('select estado,alias_id,supervisor_id from public.auditoria_planificaciones where id=$1 for update',[v.planificacionId])).rows,'Planning not found');if(plan.estado!=='planificada')throw conflict('Planning is not available for audit submission');if(plan.alias_id!==v.aliasId||plan.supervisor_id!==v.supervisorId)throw conflict('Audit does not match planning')}const items=(await c.query<{id:string}>('select id from public.auditoria_checklist_items where plantilla_id=$1',[v.plantillaId])).rows;if(items.length!==v.respuestas.length||new Set(v.respuestas.map(x=>x.itemId)).size!==items.length||!v.respuestas.every(x=>items.some(i=>i.id===x.itemId)))throw conflict('Responses must match every checklist item exactly once');const audit=one((await c.query('insert into public.auditorias(planificacion_id,alias_id,plantilla_id,fecha_realizada,supervisor_id,evaluacion_general,proxima_supervision_fecha,quejas_comentarios_cliente,otros) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *',[v.planificacionId,v.aliasId,v.plantillaId,v.fechaRealizada,v.supervisorId,v.evaluacionGeneral,v.proximaSupervisionFecha,v.quejasComentariosCliente,v.otros])).rows,'Audit creation failed');await c.query('insert into public.auditoria_respuestas(auditoria_id,item_id,resultado,observaciones) select $1,x.item_id,x.resultado,x.observaciones from jsonb_to_recordset($2::jsonb) as x(item_id uuid,resultado text,observaciones text)',[audit.id,JSON.stringify(v.respuestas.map(x=>({item_id:x.itemId,resultado:x.resultado,observaciones:x.observaciones})))]);if(v.planificacionId)await c.query("update public.auditoria_planificaciones set estado='realizada' where id=$1",[v.planificacionId]);await c.query("update public.audits_operation_idempotency set status='COMPLETED',response=$4,updated_at=now() where actor_id=$1 and operation=$2 and idempotency_key=$3",[actor,'audit_submit',key,JSON.stringify(audit)]);return{replayed:false,response:audit}})
 const createAction=(auditId:string,v:ActionCreate)=>tx(db,async c=>{if(v.respuestaId){const answer=one((await c.query<{auditoria_id:string}>('select auditoria_id from public.auditoria_respuestas where id=$1 for key share',[v.respuestaId])).rows,'Response not found');if(answer.auditoria_id!==auditId)throw conflict('Response belongs to another audit')}return one((await c.query('insert into public.auditoria_plan_accion(auditoria_id,respuesta_id,descripcion,responsable_id,fecha_limite) values($1,$2,$3,$4,$5) returning *',[auditId,v.respuestaId,v.descripcion,v.responsableId,v.fechaLimite])).rows,'Action creation failed')})
 const updateAction=(id:string,v:ActionUpdate)=>tx(db,async c=>{const old=one((await c.query<{updated_at:string|null}>('select updated_at from public.auditoria_plan_accion where id=$1 for update',[id])).rows,'Action not found');if(old.updated_at!==v.updatedAt)throw conflict('Action was modified by another user');return one((await c.query("update public.auditoria_plan_accion set estado=$2,descripcion=coalesce($3,descripcion),responsable_id=$4,fecha_limite=$5,fecha_resolucion=case when $2='resuelto' then current_date else null end where id=$1 returning *",[id,v.estado,v.descripcion??null,v.responsableId??null,v.fechaLimite??null])).rows,'Action not found')})
 const checklistCreate=(v:ChecklistCreate)=>tx(db,async c=>{const p=one((await c.query('insert into public.auditoria_checklist_plantillas(codigo_formulario,version,vigencia_desde,activa) values($1,$2,$3,false) returning *',[v.codigoFormulario,v.version,v.vigenciaDesde])).rows,'Checklist creation failed');await c.query('insert into public.auditoria_checklist_items(plantilla_id,orden,texto) select $1,x.orden,x.texto from jsonb_to_recordset($2::jsonb) x(orden int,texto text)',[p.id,JSON.stringify(v.items)]);return p})
 return{plans,createPlanning,updatePlanning,cancelPlanning,submit,createAction,updateAction,checklistCreate}
}
