import type { Db } from './pool.js'
import type pg from 'pg'
import { AppError, notFound } from '../../http/errors/app-error.js'
const s=(x:string)=>x.replace(/[A-Z]/g,m=>'_'+m.toLowerCase())
async function performImport(c:pg.PoolClient,rows:Array<Record<string,unknown>>){const codes=new Set<string>();for(const row of rows){const code=String(row.codigoInterno??'');if(code){if(codes.has(code))throw new AppError(409,'import_duplicate_code','Duplicate explicit code in import');codes.add(code)}}let created=0,updated=0;for(const row of rows){const code=String(row.codigoInterno??'');if(code){const old=await c.query('select id from public.articulos where codigo_interno=$1 for update',[code]);if(old.rows[0]){await c.query('update public.articulos set nombre=$2,categoria=$3,unidad=$4 where id=$1',[old.rows[0].id,row.nombre,row.categoria,row.unidad]);updated++}else{await c.query('insert into public.articulos(codigo_interno,nombre,categoria,unidad,activo) values($1,$2,$3,$4,true)',[code,row.nombre,row.categoria,row.unidad]);created++}}else{await c.query('insert into public.articulos(codigo_interno,nombre,categoria,unidad,activo) values(null,$1,$2,$3,true)',[row.nombre,row.categoria,row.unidad]);created++}}return{creados:created,actualizados:updated}}
async function performPriceList(c:pg.PoolClient,input:{proveedorId:string;archivoOrigen:string;rows:Array<Record<string,unknown>>}){const supplier=await c.query('select id from public.proveedores where id=$1 for update',[input.proveedorId]);if(!supplier.rows[0])throw notFound('Supplier not found');let actualizados=0,vinculados=0,pendientes=0;for(const row of input.rows){const code=String(row.codigoProveedor||row.codigoInterno||'').trim();const internal=String(row.codigoInterno??'').trim();const rel=code?(await c.query('select id from public.articulos_proveedor where proveedor_id=$1 and codigo_proveedor=$2 for update',[input.proveedorId,code])).rows[0]:null;const article=internal?(await c.query('select id from public.articulos where codigo_interno=$1',[internal])).rows[0]:null;if(rel){await c.query('update public.articulos_proveedor set articulo_id=coalesce($2,articulo_id),precio=$3,nombre_proveedor=$4,fecha_actualizacion=now() where id=$1',[rel.id,article?.id??null,row.precio,row.nombreProveedor||null]);actualizados++;continue}if(article){await c.query('insert into public.articulos_proveedor(articulo_id,proveedor_id,codigo_proveedor,nombre_proveedor,precio,activo,fecha_actualizacion) values($1,$2,$3,$4,$5,true,now())',[article.id,input.proveedorId,code||null,row.nombreProveedor||null,row.precio]);vinculados++;continue}await c.query('insert into public.articulos_proveedor_pendientes(proveedor_id,codigo_proveedor,nombre_proveedor,precio,archivo_origen,motivo) values($1,$2,$3,$4,$5,$6)',[input.proveedorId,code||null,row.nombreProveedor||null,row.precio,input.archivoOrigen,internal?`código interno indicado no encontrado: ${internal}`:(code?null:'codigo_proveedor vacío en el archivo (y sin codigo_interno para usar en su lugar)')]);pendientes++}return{actualizados,vinculadosPorCodigoInterno:vinculados,pendientesNuevas:pendientes}}
export function createCatalogRepository(db:Db){
 const one=async(q:string,p:unknown[],message:string)=>{const r=await db.query(q,p);if(!r.rows[0])throw notFound(message);return r.rows[0]}
 const patch=async(table:string,id:string,input:Record<string,unknown>,message:string)=>{const a=Object.entries(input).filter(([,v])=>v!==undefined);if(!a.length)throw new AppError(400,'invalid_payload','No fields to update');return one(`update public.${table} set ${a.map(([k],i)=>`${s(k)}=$${i+2}`).join(',')} where id=$1 returning *`,[id,...a.map(([,v])=>v)],message)}
 return {
 listSuppliers:()=>db.query('select * from public.proveedores order by razon_social,id').then(r=>r.rows), supplier:(id:string)=>one('select * from public.proveedores where id=$1',[id],'Supplier not found'),
 createSupplier:(i:Record<string,unknown>)=>one('insert into public.proveedores(razon_social,cuit,domicilio,telefono,provincia,condicion_pago_default,activo) values($1,$2,$3,$4,$5,$6,true) returning *',[i.razonSocial,i.cuit,i.domicilio,i.telefono,i.provincia,i.condicionPagoDefault],'Supplier create failed'), updateSupplier:(id:string,i:Record<string,unknown>)=>patch('proveedores',id,i,'Supplier not found'), supplierStatus:(id:string,activo:boolean)=>one('update public.proveedores set activo=$2 where id=$1 returning *',[id,activo],'Supplier not found'),
 listArticles:()=>db.query('select * from public.articulos order by nombre,id').then(r=>r.rows), article:(id:string)=>one('select * from public.articulos where id=$1',[id],'Article not found'),
 createArticle:(i:Record<string,unknown>)=>one('insert into public.articulos(codigo_interno,nombre,categoria,unidad,proveedor_habitual_id,activo) values($1,$2,$3,$4,$5,true) returning *',[i.codigoInterno??null,i.nombre,i.categoria,i.unidad,i.proveedorHabitualId??null],'Article create failed'), updateArticle:(id:string,i:Record<string,unknown>)=>patch('articulos',id,i,'Article not found'), articleStatus:(id:string,activo:boolean)=>one('update public.articulos set activo=$2 where id=$1 returning *',[id,activo],'Article not found'),
 relations:(id:string)=>db.query('select ap.*,p.razon_social from public.articulos_proveedor ap join public.proveedores p on p.id=ap.proveedor_id where ap.articulo_id=$1 order by p.razon_social,ap.id',[id]).then(r=>r.rows),
 pending:()=>db.query('select pp.*,p.razon_social from public.articulos_proveedor_pendientes pp join public.proveedores p on p.id=pp.proveedor_id where pp.resuelto=false order by pp.created_at desc,pp.id').then(r=>r.rows),
 async resolvePending(pendingId:string,articleId:string){const c=await db.pool.connect();try{await c.query('begin');const p=(await c.query('select * from public.articulos_proveedor_pendientes where id=$1 and resuelto=false for update',[pendingId])).rows[0];if(!p)throw notFound('Pending supplier article not found');const article=(await c.query('select id from public.articulos where id=$1',[articleId])).rows[0];if(!article)throw notFound('Article not found');const relation=(await c.query('insert into public.articulos_proveedor(articulo_id,proveedor_id,codigo_proveedor,nombre_proveedor,precio,activo,fecha_actualizacion) values($1,$2,$3,$4,$5,true,now()) returning *',[article.id,p.proveedor_id,p.codigo_proveedor,p.nombre_proveedor,p.precio])).rows[0];await c.query('update public.articulos_proveedor_pendientes set resuelto=true where id=$1',[pendingId]);await c.query('commit');return relation}catch(e){await c.query('rollback');throw e}finally{c.release()}},
 createRelation:(articleId:string,i:Record<string,unknown>)=>one('insert into public.articulos_proveedor(articulo_id,proveedor_id,codigo_proveedor,nombre_proveedor,precio,activo,fecha_actualizacion) values($1,$2,$3,$4,$5,coalesce($6,true),now()) returning *',[articleId,i.proveedorId,i.codigoProveedor??null,i.nombreProveedor,i.precio,i.activo],'Relation create failed'), updateRelation:(articleId:string,id:string,i:Record<string,unknown>)=>{const a=Object.entries(i).filter(([,v])=>v!==undefined);return one(`update public.articulos_proveedor set ${a.map(([k],n)=>`${s(k)}=$${n+3}`).join(',')},fecha_actualizacion=now() where id=$1 and articulo_id=$2 returning *`,[id,articleId,...a.map(([,v])=>v)],'Supplier relation not found')},
 async executeIdempotent<T extends object>(input:{actorId:string;operation:'article_import'|'price_list_apply';key:string;payloadHash:string;run:(c:pg.PoolClient)=>Promise<T>}){const c=await db.pool.connect();try{await c.query('begin');await c.query(`insert into public.catalog_operation_idempotency(actor_id,operation,idempotency_key,payload_hash,status) values($1,$2,$3,$4,'PROCESSING') on conflict do nothing`,[input.actorId,input.operation,input.key,input.payloadHash]);const existing=(await c.query('select payload_hash,status,response from public.catalog_operation_idempotency where actor_id=$1 and operation=$2 and idempotency_key=$3 for update',[input.actorId,input.operation,input.key])).rows[0] as {payload_hash:string;status:string;response:T|null};if(existing.payload_hash!==input.payloadHash)throw new AppError(409,'idempotency_key_payload_mismatch','Idempotency-Key was already used with a different payload');if(existing.status==='COMPLETED'&&existing.response){await c.query('commit');return{replayed:true,response:existing.response}}const response=await input.run(c);await c.query(`update public.catalog_operation_idempotency set status='COMPLETED',response=$4,updated_at=now() where actor_id=$1 and operation=$2 and idempotency_key=$3`,[input.actorId,input.operation,input.key,JSON.stringify(response)]);await c.query('commit');return{replayed:false,response}}catch(e){await c.query('rollback');throw e}finally{c.release()}},
 importArticles(rows:Array<Record<string,unknown>>,idempotency:{actorId:string;key:string;payloadHash:string}){return this.executeIdempotent({...idempotency,operation:'article_import',run:c=>performImport(c,rows)})},
 applyPriceList(input:{proveedorId:string;archivoOrigen:string;rows:Array<Record<string,unknown>>},idempotency:{actorId:string;key:string;payloadHash:string}){return this.executeIdempotent({...idempotency,operation:'price_list_apply',run:c=>performPriceList(c,input)})}
 }
}
export type CatalogRepository=ReturnType<typeof createCatalogRepository>
